# Generated by Django 4.2.24 on 2025-09-18 10:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('coste', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Método de entrega',
                'verbose_name_plural': 'Métodos de entrega',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='envio_coste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='envio_metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.shippingmethod'),
        ),
    ]
