# Generated by Django 4.2.24 on 2025-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_shippingmethod_pedido_envio_coste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago_metodo',
            field=models.CharField(choices=[('contrareembolso', 'Contrareembolso'), ('tarjeta', 'Tarjeta')], default='contrareembolso', max_length=20),
        ),
    ]
