# Generated by Django 4.2.24 on 2025-09-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_pago_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='envio_metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.shippingmethod'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago_metodo',
            field=models.CharField(default='contrareembolso', max_length=20),
        ),
    ]
