# Generated by Django 4.2.24 on 2025-09-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_permite_personalizacion_variante'),
        ('pedidos', '0004_alter_pedido_envio_metodo_alter_pedido_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='personalizacion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.variante'),
        ),
    ]
