# Generated by Django 4.2.24 on 2025-10-02 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre y apellidos', max_length=100)),
                ('linea1', models.CharField(max_length=120, verbose_name='Dirección')),
                ('linea2', models.CharField(blank=True, default='', max_length=120)),
                ('ciudad', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('cp', models.CharField(max_length=12, verbose_name='Código postal')),
                ('pais', models.CharField(default='ES', max_length=2)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('metodo_pago_preferido', models.CharField(choices=[('contrareembolso', 'Contrareembolso'), ('tarjeta', 'Tarjeta')], default='contrareembolso', max_length=20)),
                ('direccion_envio_pred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='accounts.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
