# Generated by Django 4.2.24 on 2025-09-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='productos_c_nombre_8571f2_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='productos_c_slug_c3e9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['nombre'], name='productos_m_nombre_46f0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['slug'], name='productos_m_slug_8223dd_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_p_categor_17b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca'], name='productos_p_marca_i_63996b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_p_activo_31f808_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado'], name='productos_p_destaca_a20b31_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='productos_p_slug_5e4b6d_idx'),
        ),
    ]
