# Generated by Django 4.2.24 on 2025-09-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permite_personalizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('extra_precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'indexes': [models.Index(fields=['producto'], name='productos_v_product_5a530b_idx'), models.Index(fields=['talla'], name='productos_v_talla_24d0ff_idx'), models.Index(fields=['color'], name='productos_v_color_678f0b_idx')],
                'unique_together': {('producto', 'talla', 'color')},
            },
        ),
    ]
