# Generated by Django 4.2.24 on 2025-11-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_permite_personalizacion_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_personalizacion_color',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo por elegir un color especial para el texto.', max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_personalizacion_nombre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo por añadir nombre/texto personalizado.', max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_personalizacion_textura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo por textura / imagen subida (logo, estampado, etc.).', max_digits=8),
        ),
    ]
